<script lang="ts">
import { supabase } from '$lib/utils/supabaseClient.js';
import { getSigner } from '$lib/utils/aaUtils';
import { API_KEY } from '$lib/config';
import { addNotification } from '$lib/utils/notifications';
import jsPDF from 'jspdf';

let invoices: any[] = $state([]);
let freelancerWallet: string = $state('');
let loading = $state(true);
let error = $state('');
let exporting = $state(false);

$effect(() => {
  async function loadInvoices() {
    try {
      loading = true;
      error = '';
      
      const signer = await getSigner();
      const address = await signer.getAddress();
      freelancerWallet = address.toLowerCase(); // Normalize to lowercase
      
      if (freelancerWallet) {
        console.log('Querying invoices for wallet:', freelancerWallet);
        
        // First try exact match
        const { data, error: supabaseError } = await supabase
          .from('invoices')
          .select('*')
          .eq('user_address', freelancerWallet)
          .order('created_at', { ascending: false });
          
        if (supabaseError) {
          console.error('Supabase query error:', supabaseError);
          throw new Error(supabaseError.message);
        }
        
        console.log('Query result:', data);
        invoices = data && Array.isArray(data) ? data : [];
        
        // If no results, try case-insensitive search
        if (invoices.length === 0) {
          console.log('No exact match, trying case-insensitive search...');
          const { data: data2, error: error2 } = await supabase
            .from('invoices')
            .select('*')
            .ilike('user_address', freelancerWallet)
            .order('created_at', { ascending: false });
            
          if (data2 && data2.length > 0) {
            console.log('Found with case-insensitive search:', data2);
            invoices = data2;
          }
        }
        
        // Temporary debug to see what we got
        if (invoices.length === 0) {
          // Check if there are any invoices at all in the table
          const { data: allInvoices } = await supabase
            .from('invoices')
            .select('user_address, project_name, created_at')
            .limit(10);
          
          console.log('No invoices found for wallet:', freelancerWallet);
          console.log('All invoices in DB:', allInvoices);
        }
      } else {
        invoices = [];
      }
    } catch (err) {
      if (err instanceof TypeError && err.message.includes('Failed to fetch')) {
        error = 'Network error: Unable to connect to the database. Please check your internet connection and try again.';
      } else {
        error = 'Failed to load invoices. Please try refreshing the page.';
      }
      invoices = [];
    } finally {
      loading = false;
    }
  }
  
  loadInvoices();
});

function getInvoiceLink(id: string) {
  return `https://nerowork.netlify.app/invoice/${id}`;
}

async function exportAllInvoicesPDF() {
  if (invoices.length === 0) return;
  
  try {
    exporting = true;
    
    const pdf = new jsPDF();
    
    // Add title
    pdf.setFontSize(20);
    pdf.text('INVOICE REPORT', 105, 30, { align: 'center' });
    
    // Add summary
    pdf.setFontSize(12);
    const totalInvoices = invoices.length;
    const paidInvoices = invoices.filter(inv => inv.status === 'paid').length;
    const totalEarned = invoices
      .filter(inv => inv.status === 'paid')
      .reduce((sum, inv) => sum + (parseFloat(inv.amount) || 0), 0);
    
    pdf.text(`Freelancer: ${freelancerWallet}`, 20, 50);
    pdf.text(`Total Invoices: ${totalInvoices}`, 20, 60);
    pdf.text(`Paid Invoices: ${paidInvoices}`, 20, 70);
    pdf.text(`Total Earned: ${totalEarned} NERO`, 20, 80);
    pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 90);
    
    // Add invoice list
    let yPosition = 110;
    pdf.text('INVOICE DETAILS:', 20, yPosition);
    yPosition += 10;
    
    invoices.forEach((invoice, index) => {
      if (yPosition > 250) {
        pdf.addPage();
        yPosition = 20;
      }
      
      pdf.setFontSize(10);
      pdf.text(`${index + 1}. ${invoice.project_name}`, 20, yPosition);
      pdf.text(`Amount: ${invoice.amount} NERO`, 120, yPosition);
      pdf.text(`Status: ${invoice.status}`, 170, yPosition);
      yPosition += 6;
      pdf.text(`Client: ${invoice.client_name}`, 25, yPosition);
      yPosition += 6;
      pdf.text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 25, yPosition);
      yPosition += 10;
    });
    
    // Add footer
    pdf.setFontSize(8);
    pdf.text('Generated by NeroWork - Web3 Freelance Platform', 105, 280, { align: 'center' });
    
    // Save the PDF
    pdf.save(`invoice-report-${new Date().toISOString().split('T')[0]}.pdf`);
    
  } catch (err) {
    console.error('Error exporting PDF:', err);
    error = 'Failed to export PDF. Please try again.';
  } finally {
    exporting = false;
  }
}
</script>

<div class="overflow-hidden rounded bg-white shadow">
  <div class="border-b border-gray-100 p-4 flex justify-between items-center">
    <h1 class="text-lg font-semibold">My Invoices</h1>
    <button 
      class="bg-green-600 text-white px-4 py-2 rounded font-semibold hover:bg-green-700 transition flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
      onclick={exportAllInvoicesPDF}
      disabled={invoices.length === 0 || exporting}
    >
      {#if exporting}
        <svg class="animate-spin -ml-1 mr-3 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Exporting...
      {:else}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
          <polyline points="14 2 14 8 20 8"></polyline>
          <line x1="16" y1="13" x2="8" y2="13"></line>
          <line x1="16" y1="17" x2="8" y2="17"></line>
          <polyline points="10 9 9 9 8 9"></polyline>
        </svg>
        Export All PDF
      {/if}
    </button>
  </div>
  
  {#if error}
    <div class="mx-4 mt-4 p-3 bg-red-50 border border-red-200 rounded-md">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <p class="text-sm text-red-800">{error}</p>
        </div>
      </div>
    </div>
  {/if}
  
  {#if loading}
    <div class="p-8 text-center">
      <div class="inline-flex items-center px-4 py-2 font-semibold leading-6 text-sm shadow rounded-md text-gray-500 bg-white">
        <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        Loading invoices...
      </div>
    </div>
  {:else if invoices.length === 0}
    <div class="p-8 text-center">
      <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48">
        <path d="M34 26H14a2 2 0 00-2 2v12a2 2 0 002 2h20a2 2 0 002-2V28a2 2 0 00-2-2zM24 8v6m0 0V8m0 6l-8-8m8 8l8-8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No invoices</h3>
      <p class="mt-1 text-sm text-gray-500">Get started by creating your first invoice.</p>
      <div class="mt-6">
        <a 
          href="/freelancer/dashboard/create-invoice" 
          class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700"
        >
          <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
          </svg>
          Create Invoice
        </a>
      </div>
    </div>
  {:else}
    <div class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead class="bg-gray-50 text-left">
        <tr>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Project</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Description</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Amount</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Status</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Transaction</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Created</th>
          <th class="px-3 py-2 font-medium text-gray-500 uppercase">Share Link</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        {#each invoices as inv}
          <tr class="hover:bg-gray-50 transition">
            <td class="px-3 py-2 font-semibold text-gray-800">{inv.project_name}</td>
            <td class="px-3 py-2 truncate max-w-xs text-gray-600">{inv.project_description}</td>
            <td class="px-3 py-2 font-mono text-blue-700">{inv.amount}</td>
            <td class="px-3 py-2">
              {#if inv.status === 'paid'}
                <span class="inline-block px-2 py-1 rounded-full text-xs font-bold bg-green-100 text-green-700 border border-green-300">Paid</span>
              {:else if inv.status === 'rejected'}
                <span class="inline-block px-2 py-1 rounded-full text-xs font-bold bg-red-100 text-red-700 border border-red-300">Rejected</span>
              {:else}
                <!-- Handle both 'pending' and legacy 'unpaid' statuses -->
                <span class="inline-block px-2 py-1 rounded-full text-xs font-bold bg-yellow-100 text-yellow-700 border border-yellow-300">
                  {inv.status === 'pending' ? 'Pending' : 'Unpaid'}
                </span>
              {/if}
            </td>
            <td class="px-3 py-2">
              {#if inv.transaction_hash}
                <a 
                  href="https://testnet.neroscan.io/tx/{inv.transaction_hash}" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  class="text-blue-600 hover:text-blue-800 text-xs underline"
                >
                  View TX
                </a>
              {:else}
                <span class="text-gray-400 text-xs">N/A</span>
              {/if}
            </td>
            <td class="px-3 py-2 text-gray-500">{new Date(inv.created_at).toLocaleString()}</td>
            <td class="px-3 py-2">
              <input class="w-36 px-1 py-0.5 border rounded text-xs bg-gray-50" readonly value={getInvoiceLink(inv.id)} />
              <button class="ml-1 px-1 py-0.5 bg-blue-100 text-blue-700 rounded text-xs border border-blue-200 hover:bg-blue-200 transition" onclick={() => navigator.clipboard.writeText(getInvoiceLink(inv.id))}>Copy</button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  {/if}
</div>
